### ISSUE TITLE
wsw_server no toma el sv_hostname correctamente

### ISSUE THREAD

**Issue by devedetti** [beigna/warsow#1]
Hola @lvm ¿me hacés la gauchada de revisar en qué le estoy pifiando?
Técnicamente estoy generando bien el string para el `sv_hostname` pero el comando `wsw_server` toma la primer palabra y nos vimos en disney. Seguramente le estoy pifiando en algo de Bash y, con de todo corazón, a esta hora (3:52) ya ni sé qué estoy programando.

Mirate esto: https://github.com/beigna/warsow/blob/07703a2f89030e425534604786cb2ce812502c50/run.sh#L6

**Comment by lvm** [comment]
Esta OK el script, pero nunca definis el valor de las variables.

sin modificarlo podes: 
```
SV_HOSTNAME=host SV_AUTOUPDATE=1 G_MAPROTATION=1 RCON_PASSWORD=s3cr3t ./run.sh
+sv_hostname "host" +sv_autoupdate 1 +g_maprotation 1 +rcon_password s3cr3t
```
(le cambie el `exec ....` por `echo...` para probar y se imprimen bien)

sino, modificando:
```
#!/bin/bash

params=""
SV_HOSTNAME=$1;
SV_AUTOUPDATE=$2;
G_MAPROTATION=$3;
RCON_PASSWORD=$4;

if [ -n "$SV_HOSTNAME" ]; then
    params+=" +sv_hostname \"${SV_HOSTNAME}\""
fi

if [ -n "$SV_AUTOUPDATE" ]; then
    params+=" +sv_autoupdate $SV_AUTOUPDATE"
fi

if [ -n "$G_MAPROTATION" ]; then
    params+=" +g_maprotation $G_MAPROTATION"
fi

if [ -n "$RCON_PASSWORD" ]; then
    params+=" +rcon_password $RCON_PASSWORD"
fi

echo $params;
```

y luego

```
./run.sh "host" 1 1 s3cr3t
```

**Comment by devedetti** [comment]
Estoy usando `env_file` en `docker compose`: https://github.com/beigna/warsow/blob/main/docker-compose.yml#L9
y los settings los toma de acá: https://github.com/beigna/warsow/blob/main/settings.env

Dentro del contenedor hice la prueba del echo y estaba todo OK, pero se ve que al hacer el `exec` en algo la pifio

**Comment by devedetti** [comment]
Dejo captura tras el nuevo merge 
![image](https://user-images.githubusercontent.com/260549/212487981-d03f0624-1e1d-44af-946d-bb8cf2dcc36f.png)
